name: Deploy & Trigger QA Tests

on:
  push:
    branches:
      - qa  # Trigger only when code is pushed to 'qa'

jobs:
  trigger-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulate Build or Deployment
        run: |
          echo "Build successful"
          echo "Code deployed to QA environment: https://qa.example.com"

      - name: Trigger Test Automation Framework
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO_PAT }}
          repository: your-org/SeleniumFrameworkInJava
          event-type: smoke-test-trigger
          client-payload: '{"baseUrl": "https://qa.example.com"}'
